CREATE DATABASE MICROMOBILITY_DB;
USE MICROMOBILITY_DB;

CREATE SCHEMA MICROMOBILITY_DB.BRONZE;
CREATE SCHEMA MICROMOBILITY_DB.SILVER;
CREATE SCHEMA MICROMOBILITY_DB.GOLD;
USE MICROMOBILITY_DB.BRONZE;

CREATE OR REPLACE TABLE MICROMOBILITY_DB.BRONZE.TRIPS_RAW(
    TRIP_ID                  VARCHAR,
    DEVICE_ID                VARCHAR,
    VEHICLE_TYPE             VARCHAR,
    TRIP_DURATION            VARCHAR,
    TRIP_DISTANCE            VARCHAR,
    START_TIME               VARCHAR,
    END_TIME                 VARCHAR,
    MODIFIED_DATE            VARCHAR,
    MONTH                    VARCHAR,
    HOUR                     VARCHAR,
    DAY_OF_WEEK              VARCHAR,
    COUNCIL_DISTRICT_START   VARCHAR,
    COUNCIL_DISTRICT_END     VARCHAR,
    YEAR                     VARCHAR,
    CENSUS_TRACT_START       VARCHAR,
    CENSUS_TRACT_END         VARCHAR,
    START_TIME_CENTRAL       VARCHAR,
    END_TIME_CENTRAL         VARCHAR,
    INGESTION_TIMESTAMP      TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_FILE              VARCHAR DEFAULT 'micromobility_raw.csv'    
);

CREATE OR REPLACE STAGE MICROMOBILITY_DB.BRONZE.RAW_STAGE
FILE_FORMAT = (
    TYPE = 'CSV'
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    SKIP_HEADER = 1
    NULL_IF = ('NULL', 'null', '', 'N/A')
    EMPTY_FIELD_AS_NULL = TRUE
    TRIM_SPACE = TRUE
);

LIST @MICROMOBILITY_DB.BRONZE.RAW_STAGE;

COPY INTO MICROMOBILITY_DB.BRONZE.TRIPS_RAW (
    TRIP_ID,
    DEVICE_ID,
    VEHICLE_TYPE,
    TRIP_DURATION,
    TRIP_DISTANCE,
    START_TIME,
    END_TIME,
    MODIFIED_DATE,
    MONTH,
    HOUR,
    DAY_OF_WEEK,
    COUNCIL_DISTRICT_START,
    COUNCIL_DISTRICT_END,
    YEAR,
    CENSUS_TRACT_START,
    CENSUS_TRACT_END,
    START_TIME_CENTRAL,
    END_TIME_CENTRAL
)
FROM @MICROMOBILITY_DB.BRONZE.RAW_STAGE
FILE_FORMAT = (
    TYPE = 'CSV'
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    SKIP_HEADER = 1
    NULL_IF = ('NULL', 'null', '', 'N/A')
    EMPTY_FIELD_AS_NULL = TRUE
    TRIM_SPACE = TRUE
)
ON_ERROR = 'CONTINUE'
PURGE = FALSE;

SELECT COUNT(*) AS TOTAL_ROWS 
FROM MICROMOBILITY_DB.BRONZE.TRIPS_RAW;

SELECT YEAR, COUNT(*) AS TRIPS
FROM MICROMOBILITY_DB.BRONZE.TRIPS_RAW
GROUP BY YEAR
ORDER BY YEAR;

SELECT 
    REPLACE(YEAR, ',', '') AS YEAR_CLEAN,
    CAST(MONTH AS INTEGER) AS MONTH_NUM,
    COUNT(*) AS TRIPS
FROM MICROMOBILITY_DB.BRONZE.TRIPS_RAW
WHERE REPLACE(YEAR, ',', '') IN ('2021', '2022')
GROUP BY YEAR_CLEAN, MONTH_NUM
ORDER BY YEAR_CLEAN, MONTH_NUM;

SELECT 
    VEHICLE_TYPE,
    REPLACE(YEAR, ',', '') AS YEAR_CLEAN,
    COUNT(*) AS TRIPS,
    ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER(PARTITION BY REPLACE(YEAR, ',', '')), 2) AS PCT_OF_YEAR
FROM MICROMOBILITY_DB.BRONZE.TRIPS_RAW
WHERE REPLACE(YEAR, ',', '') IN ('2021', '2022')
GROUP BY VEHICLE_TYPE, YEAR_CLEAN
ORDER BY YEAR_CLEAN, TRIPS DESC;

SHOW TABLES IN MICROMOBILITY_DB.BRONZE;

CREATE OR REPLACE TABLE MICROMOBILITY_DB.BRONZE.PRICING_REF (
    VEHICLE_TYPE    VARCHAR,
    UNLOCK_FEE      FLOAT,
    PER_MINUTE_RATE FLOAT
);

INSERT INTO MICROMOBILITY_DB.BRONZE.PRICING_REF VALUES
    ('scooter', 1.00, 0.39),
    ('bicycle', 1.00, 0.29),
    ('moped',   1.00, 0.39);

CREATE OR REPLACE TABLE MICROMOBILITY_DB.BRONZE.DISTRICT_REF (
    DISTRICT_ID          INTEGER,
    DISTRICT_NAME        VARCHAR,
    AREA_CLASSIFICATION  VARCHAR
);

INSERT INTO MICROMOBILITY_DB.BRONZE.DISTRICT_REF VALUES
    (1,  'District 1',  'East Austin'),
    (2,  'District 2',  'East Austin'),
    (3,  'District 3',  'South Austin'),
    (4,  'District 4',  'South Austin'),
    (5,  'District 5',  'South Austin'),
    (6,  'District 6',  'Northwest Austin'),
    (7,  'District 7',  'North Austin'),
    (8,  'District 8',  'West Austin'),
    (9,  'District 9',  'Central Austin'),
    (10, 'District 10', 'West Austin');

CREATE OR REPLACE TABLE MICROMOBILITY_DB.BRONZE.TIME_SEGMENT_REF (
    HOUR            INTEGER,
    TIME_SEGMENT    VARCHAR,
    IS_PEAK_HOUR    BOOLEAN
);

INSERT INTO MICROMOBILITY_DB.BRONZE.TIME_SEGMENT_REF VALUES
    (0,  'Late Night',    FALSE),
    (1,  'Late Night',    FALSE),
    (2,  'Late Night',    FALSE),
    (3,  'Late Night',    FALSE),
    (4,  'Late Night',    FALSE),
    (5,  'Early Morning', FALSE),
    (6,  'Early Morning', FALSE),
    (7,  'Morning Rush',  TRUE),
    (8,  'Morning Rush',  TRUE),
    (9,  'Morning Rush',  TRUE),
    (10, 'Midday',        FALSE),
    (11, 'Midday',        FALSE),
    (12, 'Midday',        FALSE),
    (13, 'Midday',        FALSE),
    (14, 'Midday',        FALSE),
    (15, 'Evening Rush',  TRUE),
    (16, 'Evening Rush',  TRUE),
    (17, 'Evening Rush',  TRUE),
    (18, 'Evening Rush',  TRUE),
    (19, 'Evening Rush',  TRUE),
    (20, 'Night',         FALSE),
    (21, 'Night',         FALSE),
    (22, 'Night',         FALSE),
    (23, 'Late Night',    FALSE);

SELECT 'PRICING_REF'     AS TABLE_NAME, COUNT(*) AS R FROM MICROMOBILITY_DB.BRONZE.PRICING_REF
UNION ALL
SELECT 'DISTRICT_REF'    AS TABLE_NAME, COUNT(*) AS R FROM MICROMOBILITY_DB.BRONZE.DISTRICT_REF
UNION ALL
SELECT 'TIME_SEGMENT_REF' AS TABLE_NAME, COUNT(*) AS R FROM MICROMOBILITY_DB.BRONZE.TIME_SEGMENT_REF;


UPDATE MICROMOBILITY_DB.BRONZE.DISTRICT_REF
SET DISTRICT_NAME = CASE DISTRICT_ID
    WHEN 1  THEN 'East Austin'
    WHEN 2  THEN 'East Austin'
    WHEN 3  THEN 'South Austin'
    WHEN 4  THEN 'South Austin'
    WHEN 5  THEN 'South Austin'
    WHEN 6  THEN 'Northwest Austin'
    WHEN 7  THEN 'North Austin'
    WHEN 8  THEN 'West Austin'
    WHEN 9  THEN 'Central Austin'
    WHEN 10 THEN 'West Austin'
END;
